account/urls.py
from django.urls import path, include
from . import views
app_name = 'account'
urlpatterns = [
    path('home/',views.home,name='home'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('signup/', views.register, name='register'),
    path('profile/', views.details, name='profile-view'),
    path('profile/<int:pk>',views.profile,name='profile-another-user'),
    path('profile/add', views.ProfileCreate.as_view(), name='profile-add'),
    path('redirect', views.loginredirect, name='login-redirect'),
    path('profile/<int:pk>/edit', views.ProfileUpdate.as_view(), name='profile-update'),
]

cabshare/urls.py
from django.urls import path, include
from . import views


app_name = 'cabshare'
urlpatterns = [
    path('',views.index,name='index'),
    path('mybookings/',views.details,name='my_bookings'),
    path('cb/',views.current_bookings,name='current_bookings'),
    path('booking/add', views.BookingCreate, name='booking-add'),
    path('booking/edit/<int:pk>', views.BookingUpdate.as_view(), name='booking-update'),
    path('booking/delete/<int:pk>', views.BookingDelete.as_view(), name='booking-delete'),
    path('booking/deleteall/', views.DeletePrevious, name='booking-delete-previous'),

    # path('active/',views.isactive,name='isactive'),
    path('search/',views.search,name='search'),
    path('results/<int:pk>/',views.results,name='results'),
    path('joinrequest/',views.joinrequest,name='joinrequest'),
    path('cancelrequest/',views.cancelrequest,name='cancelrequest'),
    path('viewrequest/<int:pk>/',views.viewrequests,name='booking-viewrequests'),
    path('viewrequestsothers/<int:pk>/',views.viewrequestsothers,name='booking-viewrequestsothers'),
    path('acceptrequest/',views.acceptrequest,name='acceptrequest'),
    path('ignorerequest/',views.ignorerequest,name='ignorerequest'),
    path('myrequests/',views.myrequests,name='myrequests'),
    path('chat/<int:pk>',views.chat,name='chat'),
    path('chat/delete/<int:pk>',views.deletechat,name='delete-chat'),
    path('messagesave/<int:pk>',views.messagesave,name='messagesave'),
    path('mychats/',views.mychats,name='mychats'),
    path('notifications/',views.notifications,name='notifications'),
    path('notifications/delete_all',views.notify_delete_all,name='notification-delete-all'),

    path('drop_booking/',views.drop_booking,name='drop_booking'),
    path('make_active/',views.make_active,name='make_active'),

    path('feedback/',views.feedback,name='feedback'),






]

cabsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cabshare/', include('cabshare.urls')),

    path('oauth/',include('social_django.urls',namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabshare/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

AREA_CHOICES = (
    ("IIT GUWAHATI", "IIT GUWAHATI"),
    ("A", "A"),
    ("B", "B"),
    ("C", "C"),
    ("D", "D"),
    ("E", "E"),
    ("F", "F"),
    ("G", "G"),
)
# When a change is made to these choices, make the corresponding changes in base.html(account and cabshare) at search.


class Booking(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    date_of_journey = models.DateField(help_text="Please use the following format: <em>YYYY-MM-DD</em>.",default=None)
    time = models.TimeField(help_text="Please use the following format: <em>HH:MM:SS</em>.",default=None)
    starting_point = models.CharField(max_length=100,choices=AREA_CHOICES,default="IIT GUWAHATI")
    destination = models.CharField(max_length=100,choices=AREA_CHOICES,default="IIT GUWAHTI")
    amount_of_luggage = models.CharField(max_length=500)
    budget = models.CharField(max_length=100)
    special_note = models.TextField(null=True,blank=True)
    is_active = models.BooleanField(default=True) #Goes inactive after completion of time, helps in searches
    drop = models.BooleanField(default=False)
    going_together = models.IntegerField(default=0)


    def get_absolute_url(self):
        return reverse('cabshare:current_bookings')

    def __str__(self):
        return "from " + self.starting_point+ " to " + self.destination + " at " + str(self.date_of_journey) + " " + str(self.time) + "-/-" +str(self.pk)

class Current_Booking(models.Model):
    booking = models.ForeignKey(Booking,on_delete=models.CASCADE)

class Request(models.Model):
    from_user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    to_booking = models.ForeignKey(Booking,on_delete=models.CASCADE)
    accept = models.BooleanField(default=False)

class Chat(models.Model):
    from_user = models.ForeignKey(User,on_delete=models.CASCADE,default=1,related_name='from_user')
    to_user = models.ForeignKey(User,on_delete=models.CASCADE,default=1,related_name='to_user')
    message = models.TextField()
    seen = models.BooleanField(default=False)

class Notification(models.Model):
    to_user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    type = models.CharField(max_length=10,default="request")
    notification = models.TextField()
    seen = models.BooleanField(default=False)

class Feedback(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    feedback = models.TextField()

cabshare/forms.py
from django import forms
from .models import Booking,Chat,Feedback
import datetime


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class BookingForm(forms.ModelForm):
    date_of_journey = forms.DateField(widget=DateInput,initial=datetime.date.today)
    time = forms.TimeField(widget=TimeInput)

    class Meta:
        model = Booking
        fields = ['date_of_journey','time','starting_point','destination','amount_of_luggage','budget','special_note']

    def clean(self):
        cleaned_data = super(BookingForm,self).clean()
        date = cleaned_data.get("date_of_journey")
        time = cleaned_data.get("time")
        starting_point = cleaned_data.get("starting_point")
        destination = cleaned_data.get("destination")
        if date <= datetime.date.today() and time <= datetime.datetime.now().time():
            raise forms.ValidationError('The date must be after or today')
        if starting_point == destination:
            raise forms.ValidationError('The starting point and destination must be different')
    # def __init__(self, *args, **kwargs):
    #         super(MyForm, self).__init__(*args, **kwargs)
    #         self.fields['time'].widget.attrs['class'] = 'clockpicker'


class ChatForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ['message']

class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['feedback']
# datetime.now()+timedelta(days=30)

cabshare/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Booking,Current_Booking,Request,Chat,Notification
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import BookingForm,ChatForm,FeedbackForm
from datetime import date, timedelta
import datetime
import time
from threading import Timer
from django.db.models import Q
import json
from django.http import JsonResponse
from django.contrib import messages

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    isactive()
    user = request.user
    bookings = Booking.objects.filter(~Q(user=user) & Q(is_active=True))
    requests = Request.objects.filter(from_user=request.user)
    to_bookings = []
    for r in requests:
        to_bookings.append(r.to_booking)
    context = {
    'user':user,
    'bookings':bookings,
    'requests':requests,
    'to_bookings':to_bookings
    }
    return render(request,'cabshare/index.html',context)

@login_required
def details(request):
    isactive()
    bookings = Booking.objects.filter(user = request.user)
    b = bookings.filter(is_active=True)
    requests=Request.objects.none()
    for booking in b:
        requests = requests | Request.objects.filter(to_booking=booking)
    context = {
    'bookings':bookings,
    'requests':requests
    }
    return render(request,'cabshare/details.html',context)
# -------------------------------------------------------------------------------------------------------------------

@login_required
def BookingCreate(request):
    if request.method=='POST':
        form = BookingForm(request.POST)

        if form.is_valid():
            booking=form.save(commit=False)
            booking.user=request.user
            booking.is_active = True
            booking.save()
            return redirect('cabshare:current_bookings')
        else:
            return render(request,'cabshare/booking_form.html',{'form':form})
    else:
        form = BookingForm(None)
        return render(request,'cabshare/booking_form.html',{'form':form})


# class BookingCreate(LoginRequiredMixin, CreateView):
#     model = Booking
#     fields = ['date_of_journey','time','destination','amount_of_luggage','budget','special_note']
#
#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         form.instance.is_active = True
#         return super(BookingCreate, self).form_valid(form)

def current_bookings(request):
    booking = Booking.objects.filter(user = request.user)
    cb = booking.order_by('-pk')[0]
    current_booking = Current_Booking(booking=cb)
    current_booking.save()
    pk = current_booking.pk
    return redirect('cabshare:results',pk)
# -------------------------------------------------------------------------------------------------------------------

def isactive():
    for b in Current_Booking.objects.all():
        if b.booking.date_of_journey > date.today():
            continue
        elif b.booking.date_of_journey == date.today():
            if b.booking.time < datetime.datetime.now().time():
                b.booking.is_active = False
                b.booking.save()
                b.delete()
            else:
                continue
        else:
            b.booking.is_active = False
            b.booking.save()
            b.delete()
    return redirect('cabshare:my_bookings')
# -------------------------------------------------------------------------------------------------------------------
class BookingUpdate(LoginRequiredMixin, UpdateView):
    model = Booking
    fields = ['date_of_journey','time','starting_point','destination','amount_of_luggage','budget','special_note']

class BookingDelete(LoginRequiredMixin, DeleteView):
    model=Booking
    success_url=reverse_lazy('cabshare:my_bookings')

    def get(self, *args, **kwargs):
            return self.post(*args, **kwargs)

@login_required
def DeletePrevious(request):
    bookings = Booking.objects.filter(user=request.user,is_active=False)
    for booking in bookings:
        booking.delete()
    return redirect('cabshare:my_bookings')
# ------------------------------------------------------------------------------------------------------------------

@login_required
def search(request):
    isactive()
    starting_point = request.GET.get('starting_point')
    destinationquery = request.GET.get('destination')
    d = request.GET.get('date')
    time = request.GET.get('time')
    #
    # from_date = time - datetime.timedelta(hours = 2)
    # to_date = time + datetime.timedelta(hours = 2)

    bookings = Booking.objects.filter(is_active=True)
    result=Booking.objects.none()
    if destinationquery and date and time:
        req = int(time[0:2])
        low = req-2
        high = req+2
        if low<0:
            low=0
        if high>23:
            high=23
        mintime = str(low)
        maxtime = str(high)

        result = bookings.filter(Q(starting_point__icontains=starting_point) & Q(destination__icontains=destinationquery) & Q(date_of_journey__icontains=d) & Q(time__hour__gte=mintime, time__hour__lte=maxtime) & ~Q(user=request.user))
    elif destinationquery and date:
        result = bookings.filter(Q(starting_point__icontains=starting_point) & Q(destination__icontains=destinationquery) & Q(date_of_journey__icontains=d) & ~Q(user=request.user))
    elif destinationquery:
        result = bookings.filter(Q(starting_point__icontains=starting_point) & Q(destination__icontains=destinationquery) & ~Q(user=request.user))
    else:
        return render(request,'cabshare/error.html')

    requests = Request.objects.filter(from_user=request.user)
    to_bookings = []
    for r in requests:
        to_bookings.append(r.to_booking)
    context = {
    'result':result,
    'requests':requests,
    'to_bookings':to_bookings
    }

    return render(request,'cabshare/search.html',context)

def results(request,pk):
    isactive()
    query = Current_Booking.objects.get(pk=pk)
    starting_point = query.booking.starting_point
    destinationquery = query.booking.destination
    d = query.booking.date_of_journey
    time = str(query.booking.time)

    req = int(time[0:2])
    low = req-2
    high = req+2
    if low<0:
        low=0
    if high>23:
        high=23
    mintime = str(low)
    maxtime = str(high)

    bookings = Booking.objects.filter(is_active=True)
    if destinationquery and date and time:
        result = bookings.filter(Q(starting_point__icontains=starting_point) & Q(destination__icontains=destinationquery) & Q(date_of_journey__icontains=d) & Q(time__hour__range=[mintime,maxtime]) & ~Q(user=request.user))

        requests = Request.objects.filter(from_user=request.user)
        to_bookings = []
        for r in requests:
            to_bookings.append(r.to_booking)
        context = {
        'result':result,
        'requests':requests,
        'to_bookings':to_bookings
        }

        return render(request,'cabshare/search.html',context)
    else:
        return render(request,'cabshare/error.html')
# ---------------------------------------------------------------------------------------------------------------------
@login_required
def joinrequest(request):
    pk = request.GET.get('inputValue')
    to_booking = Booking.objects.get(pk=pk)
    from_user = request.user
    r = Request(from_user=from_user,to_booking=to_booking)
    r.save()
    data = {
        'pk': r.pk
            }
    return JsonResponse(data)

@login_required
def cancelrequest(request):
    pk = request.GET.get('inputValue')
    r = Request.objects.get(pk=pk)
    booking = r.to_booking
    booking_pk = booking.pk
    booking_user_pk = booking.user.pk
    r.delete()
    booking_name = booking.__str__()

    type = request.GET.get('type')

    if type=="untag":
        booking.going_together = booking.going_together - 1
        booking.save()

    data = {
        'booking_pk': booking_pk,
        'booking_user_pk': booking_user_pk,
        'booking_name':booking_name
            }

    return JsonResponse(data)

# def joinrequest(request,pk):
#     to_booking = Booking.objects.get(pk=pk)
#     from_user = request.user
#     r = Request(from_user=from_user,to_booking=to_booking)
#     r.save()
#     return redirect('cabshare:index')
#
# def cancelrequest(request,pk):
#     r = Request.objects.get(pk=pk)
#     r.delete()
#
#     return redirect('cabshare:index')

@login_required
def myrequests(request):
    user = request.user
    requests = Request.objects.filter(from_user=user)
    bookings = []
    for r in requests:
        bookings.append(r.to_booking)
    re=Request.objects.all()
    context = {
        'user':user,
        'bookings':bookings,
        'requests':requests,
        're':re
    }
    return render(request,'cabshare/myrequests.html',context)
# ----------------------------------------------------------------------------------------------------------------------
@login_required
def viewrequests(request,pk):
    to_booking = Booking.objects.get(pk=pk)
    r = Request.objects.filter(to_booking=to_booking)
    user = request.user
    return render(request,'cabshare/viewrequests.html',{'requests':r,'user':user,'booking':to_booking})

@login_required
def viewrequestsothers(request,pk):
    to_booking = Booking.objects.get(pk=pk)
    r = Request.objects.filter(to_booking=to_booking)
    return render(request,'cabshare/viewrequestsothers.html',{'requests':r,'booking':to_booking})

@login_required
def acceptrequest(request):
    pk = request.GET.get('inputValue')
    re = Request.objects.get(pk=pk)
    re.accept = True
    re.save()
    to_booking = re.to_booking
    to_booking.going_together = to_booking.going_together + 1
    to_booking.save()

    data = {

cabshare/templates/cabshare/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" integrity="sha256-PHcOkPmOshsMBC+vtJdVr5Mwb7r0LkSVJPlPrp/IMpU=" crossorigin="anonymous" />
    <!-- end -->

    <!-- Icons -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- end -->

    <!-- wow.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha256-z6FznuNG1jo9PP3/jBjL6P3tvLMtSwiVAowZPOgo56U=" crossorigin="anonymous"></script>
    <script src="js/wow.min.js"></script>
             <script>
             new WOW().init();
             </script>
     <!-- end -->

     <!-- my css -->
    <link rel="stylesheet" href="{% static 'cabshare/style.css' %}" type="text/css" />
    <!-- end -->
    <title>{% block title %}CabShare{% endblock %}</title>
  </head>
  <body>
    <div class="modal" id="myModalsearch">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title"> Search </h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>

          <div class="modal-body">
            <form  action="{% url 'cabshare:search' %}" method="get">
              <div class="form-group row">
                <label for="starting_point" class="col"> Starting Point : </label>
                <div class="col">
                <select id="starting_point" name="starting_point">
                  <option value="IIT GUWAHATI">IIT GUWAHATI</option>
                  <option value="A">A</option>
                  <option value="B">B</option>
                  <option value="C">C</option>
                  <option value="D">D</option>
                  <option value="E">E</option>
                  <option value="F">F</option>
                  <option value="G">G</option>
                </select>
              </div>
              </div>

              <div class="form-group row">
                <label for="destination" class="col"> Destination : </label>
                <div class="col">
                <select id="destination" name="destination">
                  <option value="IIT GUWAHATI">IIT GUWAHATI</option>
                  <option value="A">A</option>
                  <option value="B">B</option>
                  <option value="C">C</option>
                  <option value="D">D</option>
                  <option value="E">E</option>
                  <option value="F">F</option>
                  <option value="G">G</option>
                </select>
              </div>
              </div>
              <div class="form-group row">
                <label for="date" class="col"> Date : </label>
                <div class="col">
                <input type="date" id="date" name="date" value="{{ request.GET.date}}">
                </div>
              </div>
              <div class="form-group row">
                <label for="time" class="col"> Time : </label>
                <div class="col">
                <input type="time" name="time" value="{{ request.GET.time}}">
                </div>
              </div>

              <button class="btn btn-block" type="submit" style="background-color:yellow">Search</button>
            </form>
          </div>
        </div>
      </div>
    </div>


    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
      <a class="navbar-brand" href="{% url 'cabshare:index'%}"><span style="font-family:American Typewriter, serif"><img src="{% static 'cabshare/logo.jpg' %}" alt="logo" style="height:40px; width: 150px;"></span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="topNavbar">
        <div class="mx-auto order-0">
          <button type="button" class="btn btn-light" data-toggle="modal" data-target="#myModalsearch"> Search for suitable booking... </button>
        </div>
<!-- <ul class="navbar-nav ml-auto justify-content-end">    ->Can also use this to make it align right-->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cabshare:notifications' %}" data-toggle="tooltip" data-placement="bottom" title="Notifications">
              <i class="material-icons">notifications</i>
                <span id="notifier">
                  {% if notifications_all.count %}
                    <span class="badge badge-pill badge-danger">
                        {{ notifications_all.count }}
                    </span>&nbsp;
                  {% endif %}
                </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'cabshare:booking-add' %}" data-toggle="tooltip" data-placement="bottom" title=" New Booking"><i class='fas fa-plus'></i> Add Booking&nbsp;</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"><i class='fas fa-user'></i></a>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="{% url 'account:profile-view' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'cabshare:my_bookings' %}">My Bookings</a>
              <a class="dropdown-item" href="{% url 'cabshare:myrequests' %}">My Requests</a>
              <a class="dropdown-item" href="{% url 'cabshare:mychats' %}">My Chats</a>
              <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
            </div>
          </li>&nbsp;&nbsp;&nbsp;
          <li class="nav-item"> <a href="{% url 'cabshare:feedback' %}"> <button type="button" class="btn" style="background-color:yellow"> Contact us</button> </a> </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid" style="margin-top:80px">
      {% block body %}
      {% endblock %}
    </div>
<div style="display:none">
  <input type="text" id="notification_count" value="{{ notifications_all.count }}">
</div>

    <script type="text/javascript">
      const notificationSocket = new WebSocket('ws://'+ window.location.host+ '/ws/notification/');
      notificationSocket.onmessage = function(message) {
          var d = JSON.parse(message.data);
          var from_pk = {{user.pk}};
          var ct = document.getElementById("notification_count")
          var count = Number(ct.value)
          count = count + 1
          ct.value = count.toString()
          html = '<span class="badge badge-pill badge-danger">'+ count +'</span>&nbsp;'
          if(d.to_user == from_pk && d.type!="message")
          {
            document.getElementById("notifier").innerHTML = html
          }
          if(d.type=="message")
          {
            var s = document.getElementById(d.from_user)
            var x = Number(s.value);
            x=x+1
            s.value = x.toString()
            document.getElementById(d.from_user).innerHTML = '<span class="badge badge-pill badge-success">'+ x +'</span>&nbsp;'
          }

      };

     function request(d) {
       var info = d.getAttribute('id');
       info = info.substring(7);
        var data = {
            from_user: $('#from_user_pk').val(),
            type: "request",
            to_user: d.getAttribute('value'),
            message: "Request to join you on your journey" + " "+info,
        }
        notificationSocket.send(JSON.stringify(data));
        return false;
      }

     function accept(d) {
        var st = $('#from_username').val()
        var data = {
            from_user: $('#from_user_pk').val(),
            type: "accept",
            to_user: d.getAttribute('value'),
            message: "Your request to join "+ st +" was accepted! Happy Journey!",
        }
        notificationSocket.send(JSON.stringify(data));
        return false;
      }

    $("#chatform").on("submit", function(event) {
      var data = {
        from_user: $('#from_user_pk').val(),
        type: "message",
        to_user: $('#to_user_pk').val(),
        message: "You have a message",
    }
    notificationSocket.send(JSON.stringify(data));
    return false;
   });
    </script>

  </body>
</html>

cabshare/templates/cabshare/booking_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'cabshare:my_bookings' %}"><button type="button" class="btn btn-light">No! Go back </button></a>
</form>

cabshare/templates/cabshare/booking_form.html
{% extends 'cabshare/base.html'%}

{% block title%} Add Booking {% endblock %}

{% block body %}
<style>
.card-body {
  background: rgba(6, 4, 4, 0.6);
 }
</style>

<div class="card-body" style="width:1000px">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'cabshare/form-template.html' %}
      <!-- <p><label for="id_date_of_journey">Date of Journey   : &nbsp; </label><input type="date" name="date" id="id_date_of_journey"></p>
      <p><label for="id_time">Time              : &nbsp; </label><input type="time" name="time" id="id_time"></p>
      <p><label for="id_destination">Destination       : &nbsp; </label><input type="text" name="destination" id="id_destination"></p>
      <p><label for="id_amount_of_luggage">Amount of Luggage : &nbsp; </label><input type="text" name="luggage" id="id_amount_of_luggage"></p>
      <p><label for="id_budget">Budget            : &nbsp; </label><input type="text" name="budget" id="id_budget"></p>
      <p><label for="id_special_note">Special Note      : &nbsp; </label><input type="text" name="special_note" id="id_special_note"></p> -->

    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-block" style="background-color:yellow">Submit</button>
      </div>
    </div>
  </form>
</div>

{% endblock %}

cabshare/templates/cabshare/notifications.html
{% extends 'cabshare/base.html' %}

{% block title %} Notifications {% endblock %}

{% block body %}
{% load filters %}
<div class="card" style="height:85vh;background: rgba(6, 4, 4, 0.6);" id="overflow">
<div id="chat" class="card-body">
  <div align="right">
    <a href="{% url 'cabshare:notification-delete-all' %}"><button type="button" class="btn btn-danger">Delete all</button></a>
  </div>
  {% if notifications %}
    <div class="table-responsive" >
       <table class="table table-hover">
         <thead style="border-color:white">
           <tr>
             <th style="color:white;">No.</th>
             <th style="color:white;">Notifications</th>
           </tr>
         </thead>
         <tbody>
           {% for notification in notifications %}
             <tr>
               <td style="color:white;"> {{ forloop.counter }} </td>
               {% if notification.type == "request" %}
                <td>
                   {% with notification.notification|split:"-/-" as parts %}
                     <a href="{% url 'cabshare:booking-viewrequests' parts|last %}" style="{% if forloop.counter > unseen%}color:white;{% endif %}">{{ parts|first }}</a>
                   {% endwith %}
                </td>
               {% elif notification.type == "accept" %}
                <td> <a href="{% url 'cabshare:myrequests' %}" style="{% if forloop.counter > unseen%}color:white;{% endif %}">{{ notification.notification }}</a></td>
               {% else %}
                <td> <a href="{% url 'cabshare:mychats' %}" style="{% if forloop.counter > unseen%}color:white;{% endif %}">{{ notification.notification }}</a> </td>
               {% endif %}
             </tr>
            {% endfor %}
         </tbody>
       </table>
     </div>

  {% else %}
    <h3 style="color:white"> No notifications to show </h3>
  {% endif %}
</div>
</div>

  <script type="text/javascript">

    onload = function() {
      document.getElementById("overflow").style.overflow = "auto";
    };

  </script>
{% endblock %}